=== marcossilvestrini/portfolio/.astro/collections/certificacoes.schema.json
{
  "$ref": "#/definitions/certificacoes",
  "definitions": {
    "certificacoes": {
      "type": "object",
      "properties": {
        "tipo": {
          "type": "string"
        },
        "titulo": {
          "type": "string"
        },
        "instituicao": {
          "type": "string"
        },
        "ano": {
          "type": "string"
        },
        "descricao": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "tipo",
        "titulo",
        "instituicao",
        "ano"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== marcossilvestrini/portfolio/src/content/certificacoes/03-lpic2.json
{
  "tipo": "certificacao",
  "titulo": "LPIC-2 - Linux Engineer",
  "instituicao": "lpi.org",
  "ano": "2022 - 2023",
  "descricao": "O LPIC-2 é a segunda certificação no programa de certificação profissional de múltiplos níveis do Linux do Linux Professional Institute (LPI). Valida a capacidade de administrar redes mistas de pequeno a médio porte. Composta pelos exames 201-450 e 202-450."
}

=== marcossilvestrini/portfolio/src/content/certificacoes/02-lpic1.json
{
  "tipo": "certificacao",
  "titulo": "LPIC-1 - Linux Administrator",
  "instituicao": "lpi.org",
  "ano": "2022",
  "descricao": "O LPIC-1 é a primeira certificação no programa de certificação profissional em vários níveis do Linux do Linux Professional Institute (LPI). Composta pelos exames 101-500 e 102-500."
}

=== marcossilvestrini/portfolio/src/content/certificacoes/04-az900.json
{
  "tipo": "certificacao",
  "titulo": "Azure AZ-900 Microsoft Azure Fundamentals",
  "instituicao": "microsoft.com",
  "ano": "2023",
  "descricao": "O exame de Fundamentos do Azure é uma oportunidade de comprovar o conhecimento dos conceitos de nuvem, serviços do Azure, cargas de trabalho do Azure, segurança e privacidade no Azure, bem como preços e suporte do Azure."
}
